

package org.jetbrains.kotlin.compiler.plugin.template.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.compiler.plugin.template.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  private void run(String fileName) {
    runTest("compiler-plugin/testData/diagnostics/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("anotherDiagnosticTest.kt")
  public void testAnotherDiagnosticTest() {
    run("anotherDiagnosticTest.kt");
  }

  @Test
  @TestMetadata("ifElseMissingAssignment.kt")
  public void testIfElseMissingAssignment() {
    run("ifElseMissingAssignment.kt");
  }

  @Test
  @TestMetadata("ifWithoutElse.kt")
  public void testIfWithoutElse() {
    run("ifWithoutElse.kt");
  }

  @Test
  @TestMetadata("requiredMessage.kt")
  public void testRequiredMessage() {
    run("requiredMessage.kt");
  }

  @Test
  @TestMetadata("requiredMessages.kt")
  public void testRequiredMessages() {
    run("requiredMessages.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    run("simple.kt");
  }

  @Test
  @TestMetadata("whenMissingAssignment.kt")
  public void testWhenMissingAssignment() {
    run("whenMissingAssignment.kt");
  }

  @Test
  @TestMetadata("whenWithoutElse.kt")
  public void testWhenWithoutElse() {
    run("whenWithoutElse.kt");
  }
}
